// Code generated by goctl. DO NOT EDIT.
package types

type AcceptRequest struct {
	Series string `form:"series"`
	Key    string `form:"key, optional"`
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
